export const NewsCategories = {
  heyatRaeesah: {
    id: 2,
    name: 'جلسات هیئت رئیسه',
    title: 'جلسات هیئت رئیسه',
    slug: 'jalasat-heyat-raeesah',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  majmaOmoomi: {
    id: 3,
    name: 'جلسات مجمع عمومی',
    title: 'جلسات مجمع عمومی',
    slug: 'jalasat-majma-omoomi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  majmaOstani: {
    id: 4,
    name: 'جلسات مجمع استانی',
    title: 'جلسات مجمع استانی',
    slug: 'jalasat-majma-ostani',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  mosahebeHeyatRaeeseh: {
    id: 6,
    name: 'مصاحبه هیئت رئیسه',
    title: 'مصاحبه هیئت رئیسه',
    slug: 'mosahebe-heyat-raeesah',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  mosahebeRoasaOstan: {
    id: 7,
    name: 'مصاحبه رؤسای مجامع استانی',
    title: 'مصاحبه رؤسای مجامع استانی',
    slug: 'mosahebe-roasa-majame-ostani',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  mosahebeRoasaCommission: {
    id: 8,
    name: 'مصاحبه رؤسای کمیسیون ها',
    title: 'مصاحبه رؤسای کمیسیون ها',
    slug: 'mosahebe-roasa-commission',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  mosahebeNamayandeCity: {
    id: 9,
    name: 'مصاحبه نمایندگان شهرها',
    title: 'مصاحبه نمایندگان شهرها',
    slug: 'mosahebe-namayandegan',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionSeeyasi: {
    id: 10,
    name: 'کمیسیون سیاسی',
    title: 'کمیسیون سیاسی',
    slug: 'commission-seeyasi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionFaraminEmam: {
    id: 11,
    name: 'کمیسیون پیگیری فرامین امام و رهبری',
    title: 'کمیسیون پیگیری فرامین امام و رهبری',
    slug: 'commission-faramin-emam-rahbari',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionHozeDaneshgah: {
    id: 12,
    name: 'کمیسیون حوزه و دانشگاه',
    title: 'کمیسیون حوزه و دانشگاه',
    slug: 'commission-hoze-daneshgah',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionTarhBarname: {
    id: 13,
    name: 'کمیسیون طرح و برنامه',
    title: 'کمیسیون طرح و برنامه',
    slug: 'commission-tarh-barname',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionTahqiqatElmi: {
    id: 14,
    name: 'کمیسیون تحقیقات علمی',
    title: 'کمیسیون تحقیقات علمی',
    slug: 'commission-Tahqiqat-elmi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionTashkilatElmi: {
    id: 14,
    name: 'کمیسیون تشکیلات علمی',
    title: 'کمیسیون تشکیلات علمی',
    slug: 'commission-Tashkilat-elmi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionTahqiqBarresi: {
    id: 16,
    name: 'کمیسیون تحقیق و بررسی',
    title: 'کمیسیون تحقیق و بررسی',
    slug: 'commission-tahqiq-barresi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionjazbGozinesh: {
    id: 17,
    name: 'کمیسیون جذب و گزینش',
    title: 'کمیسیون جذب و گزینش',
    slug: 'commission-jazb-gozinesh',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionMaliEqtesadi: {
    id: 18,
    name: 'کمیسیون مالی و اقتصادی',
    title: 'کمیسیون مالی و اقتصادی',
    slug: 'commission-mali-eqtesadi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionTabilqat: {
    id: 19,
    name: 'کمیسیون تبلیغات',
    title: 'کمیسیون تبلیغات',
    slug: 'commission-tabliqat',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionBasijAmadegi: {
    id: 20,
    name: 'کمیسیون بسیج و آمادگی',
    title: 'کمیسیون بسیج و آمادگی',
    slug: 'commission-basij-amadegi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionAmoozesh: {
    id: 21,
    name: 'کمیسیون آموزش',
    title: 'کمیسیون آموزش',
    slug: 'commission-amoozesh',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionAkhlaq: {
    id: 22,
    name: 'کمیسیون اخلاق',
    title: 'کمیسیون اخلاق',
    slug: 'commission-akhlaq',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
  commissionFazaMajazi: {
    id: 23,
    name: 'کمیسیون فضای مجازی',
    title: 'کمیسیون فضای مجازی',
    slug: 'commission-faza-majazi',
    seoDescription: 'مهمترین اخبار را در سایت خبری ما دنبال کنید',
  },
} as const;

export type NewsCategoryKey = keyof typeof NewsCategories;

export function getCategoryInfo(category: NewsCategoryKey) {
  return NewsCategories[category];
}
